const yomama = [
	{ 'number': 1, 'yomama': 'Yo mama is so fat that her bellybutton gets home 15 minutes before she does.' },
	{ 'number': 2, 'yomama': 'Yo mama is so fat that when she was diagnosed with a flesh-eating disease, the doctor gave her ten years to live.' },
	{ 'number': 3, 'yomama': 'Yo mama is so fat that the National Weather Service names each one of her farts.' },
	{ 'number': 4, 'yomama': 'Yo mama is so fat and dumb that the only reason she opened her email was because she heard it contained spam.' },
	{ 'number': 5, 'yomama': 'Yo mama is so fat she threw on a sheet for Halloween and went as Antarctica.' },
	{ 'number': 6, 'yomama': 'Yo mama is so fat that she looked up cheat codes for Wii Fit' },
	{ 'number': 7, 'yomama': 'Yo mama is so fat that the only exercise she gets is when she chases the ice cream truck.' },
	{ 'number': 8, 'yomama': 'Yo mama is so fat that she sat on a dollar and squeezed a booger out George Washington\'s nose.' },
	{ 'number': 9, 'yomama': 'Yo mama is so fat that when she gets in an elevator, it has to go down.' },
	{ 'number': 10, 'yomama': 'Yo mama is so fat that when her beeper goes off, people think she\'s backing up.' },
	{ 'number': 11, 'yomama': 'Yo mama is so fat that she has to iron her pants on the driveway.' },
	{ 'number': 12, 'yomama': 'Yo mama is so fat that she left the house in high heels and came back wearing flip flops.' },
	{ 'number': 13, 'yomama': 'Yo mama is so fat that people jog around her for exercise.' },
	{ 'number': 14, 'yomama': 'Yo mama is so fat that she was floating in the ocean and Spain claimed her for the New World.' },
	{ 'number': 15, 'yomama': 'Yo mama is so fat that when she walked in front of the TV, I missed 3 seasons of Breaking Bad.' },
	{ 'number': 16, 'yomama': 'Yo mama is so fat that you have to grease the door frame and hold a twinkie on the other side just to get her through!' },
	{ 'number': 17, 'yomama': 'Yo mama is so fat that that when she sits on the beach, Greenpeace shows up and tries to tow her back into the ocean...' },
	{ 'number': 18, 'yomama': 'Yo mama is so ugly that she looked out the window and got arrested for mooning.' },
	{ 'number': 19, 'yomama': 'Yo mama is so ugly that people go as her for Halloween.' },
	{ 'number': 20, 'yomama': 'Yo mama is so ugly that she turned Medusa to stone!' },
	{ 'number': 21, 'yomama': 'Yo mama is so ugly that the government moved Halloween to her birthday!' },
	{ 'number': 22, 'yomama': 'Yo mama is so ugly that she scares the roaches away.' },
	{ 'number': 23, 'yomama': 'Yo mama is so ugly that she makes blind children cry.' },
	{ 'number': 24, 'yomama': 'Yo mama is so ugly that her shadow ran away from her.' },
	{ 'number': 25, 'yomama': 'Yo mama is so ugly that her birth certificate contained an apology letter from the condom factory.' },
	{ 'number': 26, 'yomama': 'Yo mama is so ugly that she tried to take a bath and the water jumped out!' },
	{ 'number': 27, 'yomama': 'Yo mama is so ugly that she made an onion cry!' },
	{ 'number': 28, 'yomama': 'Yo mama is so ugly that when she looks in the mirror it says \"viewer discretion is advised.\"' },
	{ 'number': 29, 'yomama': 'Yo mama is so nasty that I chatted with her on MSN and she gave me a virus.' },
	{ 'number': 30, 'yomama': 'Yo mama is so nasty that I when I talked to her on the phone, she gave me an ear infection.' },
	{ 'number': 31, 'yomama': 'Yo mama is so old that that when she was in school there was no history class.' },
	{ 'number': 32, 'yomama': 'Yo mama is so old that her social security number is 1.' },
	{ 'number': 33, 'yomama': 'Yo mama is so fat that light bends around her.' },
	{ 'number': 34, 'yomama': 'Yo mama is so fat that I took a picture of her last Christmas and it\'s still printing!' },
	{ 'number': 35, 'yomama': 'Yo mama is so fat that she gets group insurance.' },
	{ 'number': 36, 'yomama': 'Yo mama is so fat she blew up the Deathstar."' }

];
module.exports = yomama;
